version: '3'
services:
  mysql:
    image: "mysql:8-debian"
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: magetest_dev
      MYSQL_USER: magetest
      MYSQL_PASSWORD: password123
  php:
    image: php:8.2-fpm
    build:
      context: ./docker/php
    volumes:
      - ./:/srv/magetest
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.template:/etc/nginx/templates/default.conf.template:ro
      - ./:/srv/magetest
    ports:
      - "8080:80"
    links:
      - php
    environment:
      - NGINX_HOST=_
      - NGINX_PORT=80
      - NGINX_ROOT=/srv/magetest/magento-root
      - NGINX_PROXY=php:9000
    depends_on:
      - php
  magetest_setup:
    image: php:8.2-fpm
    volumes:
      - ./:/srv/magetest
    restart: "no"
    environment:
      - OPENMAGE_ROOT=/srv/magetest/magento-root
      - OPENMAGE_VERSION=v20.0.20
    depends_on:
      - php
    entrypoint: ['/usr/bin/env', 'bash', '-c', '/srv/magetest/docker/setup.sh']
  magetest_test:
    image: php:8.2-fpm
    volumes:
      - ./:/srv/magetest
    restart: "no"
    environment:
      - OPENMAGE_ROOT=/srv/magetest/magento-root
    depends_on:
      - php
#    entrypoint: ['/usr/bin/env', 'bash', '-c', 'cd /srv/magetest/magento-root && ./vendor/bin/phpunit']
